### ISSUE TITLE
Unhandled Exception: Instance of 'CancelledException'

### ISSUE THREAD

**Issue by msxenon** [JonathanPeterCole/dart-cancellation-token#1]
I have just attached some functions (asCancellable) 
but sometimes I get this error without any stack trace so it's a little bit weird!
My whole app is running under "runZoned" and I'm using stack_trace package to catch all unhandled issues but its not catching only this 
[ +353 ms] E/flutter ( 7897): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Instance of 'CancelledException'

**Comment by JonathanPeterCole** [comment]
I've just pushed up some changes to the dev branch to attempt to resolve this. Please try the following in your pubspec.yaml to test the change and let me know if you're still seeing the issue.
```yaml
dependencies:   
  cancellation_token:
    git:
      url: git://github.com/JonathanPeterCole/dart-cancellation-token.git
      ref: dev
```
